# Iceberg Data Generator Configuration File

[catalog]
type = "rest"
uri = "http://localhost:8181"
s3_endpoint = "http://localhost:9000"
s3_access_key_id = "admin"
s3_secret_access_key = "password"
s3_region = "us-east-1"

# Database and table configuration
[table]
namespace = "name1"
table_name = "test_table"

# Data files configuration
[data_files]
# Number of rows per data file
rows_per_file = 1000
# Number of data files
file_count = 5

# Position Delete files configuration
[pos_delete_files]
# Number of rows per position delete file
rows_per_file = 1000
# Number of position delete files
file_count = 2

# Equality Delete files configuration
[equality_delete_files]
# Number of rows per equality delete file
rows_per_file = 1000
# Number of equality delete files
file_count = 2

